import { Geist, Geist_Mono, Pacifico, Lexend, Archivo_Narrow } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pacificoFont = Pacifico({
  subsets:["latin"],
  weight: "400",
  variable: "--font-pacifico"
})

const lexendFont = Lexend({
  variable: "--font-lexend",
  weight:["400","600","900"],
  subsets: ["latin"]
})

const archivoNFont = Archivo_Narrow({
  weight: ["600","700"],
  variable: "--font-archivo",
  subsets: ["latin"]
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${pacificoFont.variable} ${lexendFont.variable} ${archivoNFont.variable} antialiased !bg-white`}
      >
        {children}
      </body>
    </html>
  );
}
